# Generated by Django 3.2.6 on 2021-08-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('pic_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1000)),
                ('pic_url', models.URLField(blank=True, null=True)),
                ('price_value', models.IntegerField(default=None, max_length=100000)),
                ('price_currency', models.CharField(default=None, max_length=20)),
                ('dimension_value', models.IntegerField(default=None, max_length=1000)),
                ('dimension_unit', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
